[supabase]
url = "https://ondljkgjqvgbhnixvsei.supabase.co"
key = "sb_secret_XgFLk4nizGiuA79OmJoRbA_mDU4ZJC1" 

[gemini]
GEMINI_API_KEY = "AIzaSyAes0EElbsnA_8E6J7HVnXYGXNNu-5uK0w"

[admin]
password = "admin@26"